language: java

sudo: required

env:
  - MONGODB_PORT_27017_TCP_ADDR="127.0.0.1"

services:
  - docker
  - mongodb

script:
  - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
  - ./gradlew test
  - docker build --tag desp/glickorater:${TRAVIS_COMMIT} .
  - docker push desp/glickorater:${TRAVIS_COMMIT}

