version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-wrapper-{{ .Environment.CACHE_VERSION }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - restore_cache:
          keys:
            - gradle-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "build.gradle" }}

      - run:
          name: Build Project
          command: ./gradlew --max-workers 2 --continue clean shadowJar --info

      - store_test_results:
          path: ./build/test-results/

      - store_artifacts:
          path: ./build/libs/
          prefix: libs

      - run:
          name: Copy libs to workspace
          command: mkdir -p ./ws && cp -r ./build ./ws

      - persist_to_workspace:
          root: ./ws/
          paths: ./build/libs/

      - save_cache:
          paths:
            - ~/.gradle/wrapper/
          key: gradle-wrapper-{{ .Environment.CACHE_VERSION }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - save_cache:
          paths:
            - ~/.gradle/caches/
          key: gradle-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "build.gradle" }}

  publish-to-github:
    docker:
      - image: cibuilds/github:0.10

    steps:
      - checkout

      - attach_workspace:
          at: ./ws/

      - run:
          name: "Publish Release on GitHub"
          command: |
            TAG=$(git describe --tags)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${TAG} ./ws/build/libs

  publish-to-docker-hub:
    docker:
      - image: cibuilds/docker:18.06.1

    steps:
      - checkout

      - attach_workspace:
          at: ./ws/

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push docker image
          command: |
            cp -r ./ws/build ./build
            docker build --tag desp/glickorater:${CIRCLE_SHA1} .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push desp/glickorater:${CIRCLE_SHA1}

  deploy:
    docker:
      - image: desp/kubectl:1.12.2

    steps:
      - checkout

      - run:
          name: Deploy to k8s
          command: |
            mkdir -p ~/.kube/
            echo ${KUBECONFIG_AS_BASE64} | base64 -d > ~/.kube/config
            kubectl -n glickorater set image deployment/glickorater glickorater=desp/glickorater:${CIRCLE_SHA1} --record=true

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-to-github:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-to-docker-hub:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - publish-to-docker-hub
          filters:
            branches:
              only: master
