version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-wrapper-{{ .Environment.CACHE_VERSION }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - restore_cache:
          keys:
            - gradle-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "build.gradle" }}

      - run:
          name: Build Project
          command: ./gradlew --max-workers 2 --continue clean shadowJar --info

      - store_test_results:
          path: ./build/test-results/

      - store_artifacts:
          path: ./build/libs/glicko-rater-1.0.jar
          prefix: jar

      - persist_to_workspace:
          root: ./build/libs
          paths: glicko-rater-1.0.jar

      - save_cache:
          paths:
            - ~/.gradle/wrapper/
          key: gradle-wrapper-{{ .Environment.CACHE_VERSION }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - save_cache:
          paths:
            - ~/.gradle/caches/
          key: gradle-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "build.gradle" }}

  publish-to-github:
    docker:
      - image: cibuilds/github:0.10

    steps:
      - checkout

      - attach_workspace:
          at: ./build/libs

      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(git describe --tags)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/libs

  publish-to-docker-hub:
    docker:
      - image: cibuilds/docker:18.06.1

    steps:
      - checkout

      - attach_workspace:
          at: ./build/libs

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push docker image
          command: |
            VERSION=$(git describe --tags)
            docker build --tag desp/glickorater:${VERSION} .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push desp/glickorater:${VERSION}

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-to-github:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - publish-to-docker-hub:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /.*/
